# Generated by Django 5.2 on 2025-04-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_description', models.TextField()),
                ('client_country', models.CharField(max_length=100)),
                ('client_city', models.CharField(max_length=100)),
                ('client_hostname', models.CharField(max_length=100)),
                ('client_router_prefix', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=100)),
                ('client_data_center', models.CharField(max_length=100)),
            ],
        ),
    ]
